# Generated by Django 2.2.3 on 2019-07-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-publication_date'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'feeds'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='published',
            new_name='publication_date',
        ),
    ]
